description "BBQCoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env bbqcoind_BIN="/usr/bin/bbqcoind"
env bbqcoind_USER="bbqcoin"
env bbqcoind_GROUP="bbqcoin"
env bbqcoind_PIDDIR="/var/run/bbqcoind"
# upstart can't handle variables constructed with other variables
env bbqcoind_PIDFILE="/var/run/bbqcoind/bbqcoind.pid"
env bbqcoind_CONFIGFILE="/etc/bbqcoin/bbqcoin.conf"
env bbqcoind_DATADIR="/var/lib/bbqcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # bbqcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$bbqcoind_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bbqcoind."
        echo "The setting must appear in $bbqcoind_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BBQCoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$bbqcoind_PIDDIR"
    chmod 0755 "$bbqcoind_PIDDIR"
    chown $bbqcoind_USER:$bbqcoind_GROUP "$bbqcoind_PIDDIR"
    chown $bbqcoind_USER:$bbqcoind_GROUP "$bbqcoind_CONFIGFILE"
    chmod 0660 "$bbqcoind_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$bbqcoind_PIDFILE" \
    --chuid $bbqcoind_USER:$bbqcoind_GROUP \
    --exec "$bbqcoind_BIN" \
    -- \
    -pid="$bbqcoind_PIDFILE" \
    -conf="$bbqcoind_CONFIGFILE" \
    -datadir="$bbqcoind_DATADIR" \
    -disablewallet \
    -daemon

